version: '2'

x-logging: &log-journald
  driver: journald
  options:
    tag: montagu

services:
  api:
    image: ${ORG}/montagu-api:master
    ports:
     - "8080:8080"
    networks:
     - proxy
    depends_on:
     - db
    volumes:
     - token_key_volume:/etc/montagu/api/token_key
     - ${PWD}/montagu_emails:/tmp/montagu_emails
  db:
    image: ${ORG}/montagu-db:master
    ports:
     - "5432:5432"
    command: /etc/montagu/postgresql.test.conf
    networks:
     - proxy
  contrib:
    image: ${ORG}/montagu-contrib-portal:master
    networks:
     - proxy
    depends_on:
     - api
    volumes:
     - template_volume:/usr/share/nginx/html/templates
     - guidance_volume:/usr/share/nginx/html/guidance
  admin:
    image: ${ORG}/montagu-admin-portal:master
    networks:
     - proxy
    depends_on:
     - api
  static:
    image: ${ORG}/montagu-static:master
    networks:
     - proxy
    volumes:
    - static_volume:/www
    - static_logs:/var/log/caddy
volumes:
  template_volume:
  guidance_volume:
  static_logs:
  static_volume:
  token_key_volume:
networks:
  proxy: